# Generated by Django 5.0.6 on 2024-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название версии'),
        ),
    ]
